name: Windows (personal user account)

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Create user account
      run: C:\Windows\system32\net.exe user $Env:RDP_USERNAME /add
      env:
        RDP_USERNAME: ${{ secrets.RDP_USERNAME }}
    - name: Setting password for user account
      run: C:\Windows\system32\net.exe user $Env:RDP_USERNAME $Env:RDP_PASSWORD
      env:
        RDP_USERNAME: ${{ secrets.RDP_USERNAME }}
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
    - name: Giving administrator access for user account
      run: C:\Windows\system32\net.exe localgroup Administrators $Env:RDP_USERNAME /add
      env:
        RDP_USERNAME: ${{ secrets.RDP_USERNAME }}
      env:
        RDP_USERNAME: ${{ secrets.RDP_USERNAME }}
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
      
